Query:
  type: object
  config:
    description: "Articles ORM repository"
    fields:
        article:
            type: "Article"
            args:
                id:
                    description: "Resolves using the article id"
                    type: "Int"
            resolve: "@=resolver('Article', [args])"
        articles_list:
            type: "ArticleList"
            args:
                limit:
                    description: "limit"
                    type: "Int"
            resolve: "@=resolver('ArticleList', [args])"
        tag:
            type: "Tag"
            args:
                id:
                    description: "Resolves using the tag id"
                    type: "Int"
            resolve: "@=resolver('Tag', [args])"
        tags_list:
            type: "TagList"
            args:
                limit:
                    description: "limit"
                    type: "Int"
            resolve: "@=resolver('TagList', [args])"
         

